import Image from 'next/image';
import Link from 'next/link';
import type { Metadata } from 'next';

import SideBar from '@/app/components/SideBar';

import './globals.scss';
import styles from './Layout.module.scss';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Star Wars',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={styles.body}>
        <header className={styles.header}>
          <Link href="/">
            <Image src='/images/sw_logo_yellow.png' width={200} height={90} alt='star wars logo'/>
          </Link>
        </header>
        <div className={styles.container}>
          <aside>
            <SideBar />
          </aside>
          <main className={styles.main}>{children}</main>
        </div>
        <footer className={styles.footer}>
          <p>All rights reserved®</p>
        </footer>
      </body>
    </html>
  )
}
